Projekt/Hospital/PresentationLayer/Controllers/AilmentController.cs
using BusinessLayer.DataTransferObjects;
using BusinessLayer.DataTransferObjects.Filters;
using BusinessLayer.Facades;
using BusinessLayer.Services.Users;
using PresentationLayer.Helpers;
using PresentationLayer.Models;
using PresentationLayer.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;


namespace PresentationLayer.Controllers
{

    public class AilmentsController : BaseController
    {

        // GET: Ailment
        public AilmentFacade AilmentFacade { get; set; }

        readonly int symptomItemsPerPage = 21;
        readonly int ailmentItemsPerPage = 20;

        [PermissionAuthorize(Permission.viewAilments)]
        public async Task<ActionResult> Index(AilmentListModel model = null, int ailmentPage = 1, int symptomPage = 1)
        {
            model = model ?? new AilmentListModel();

            var ailmentFilter = new AilmentFilterDto
            {
                    Name = model.AilmentNameFilter,
                    PageSize = ailmentItemsPerPage,
                    RequestedPageNumber = ailmentPage
            };

            if (model.SymptomGuidsFilter != null && model.SymptomGuidsFilter.Any())
            {
                var ailmentSymptoms = (await AilmentFacade.GetAilmentSymptomsAsync(new AilmentSymptomFilterDto {AnySymptom = model.SymptomGuidsFilter.ToArray()})).Items;
                Guid[] ailmentIdsWithAtLeastOneFilteredSymptom = ailmentSymptoms.Select(asy => asy.AilmentId).ToArray();
                var ailmentsWithAllSymptoms = ailmentIdsWithAtLeastOneFilteredSymptom.Select(async id => new
                {
                        AilmentId = id,
                        SymptomIds = (await AilmentFacade.GetAilmentSymptomsAsync(new AilmentSymptomFilterDto {AilmentId = id})).Items.Select(asy => asy.SymptomId).ToList()
                });

                var ailmentIds = new List<Guid>();
                foreach (var ailmentWithSymptoms in ailmentsWithAllSymptoms)
                {
                    var ASresult = await ailmentWithSymptoms;
                    bool isOk = true;
                    foreach (Guid requiredSymptomId in model.SymptomGuidsFilter)
                    {
                        if (!ASresult.SymptomIds.Contains(requiredSymptomId))
                        {
                            isOk = false;
                            break;
                        }
                    }
                    if (isOk)
                    {
                        ailmentIds.Add(ASresult.AilmentId);
                    }
                }


                ailmentFilter.AnyId = ailmentIds.ToArray();

                if (ailmentFilter.AnyId != null && ailmentFilter.AnyId.Any())
                {
                    var result = await AilmentFacade.GetAilmentsAsync(ailmentFilter);
                    model.Ailments = new PagedList.StaticPagedList<AilmentDto>(result.Items.ToList(), ailmentPage, ailmentItemsPerPage, (int) result.TotalItemsCount);
                }
                else
                {
                    model.Ailments = new PagedList.StaticPagedList<AilmentDto>(new List<AilmentDto>(), 1, ailmentItemsPerPage, 0);
                }
            }
            else
            {
                var result = await AilmentFacade.GetAilmentsAsync(ailmentFilter);
                model.Ailments = new PagedList.StaticPagedList<AilmentDto>(result.Items.ToList(), ailmentPage, ailmentItemsPerPage, (int) result.TotalItemsCount);
            }
            //model.AilmentFilter = ailmentFilter;
            //model.SymptomFilter = model.SymptomFilter ?? new SymptomFilterDto();
            model.Symptoms = await GetAllSymptoms(symptomPage);

            return View("AilmentsView", model);
        }


        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> Create()
        {
            var model = new AilmentCreateModel
            {
                    Symptoms = await GetAllSymptoms(1),
                    SymptomFilterActionName = nameof(FilterAilmentEdit)
            };
            return View("AilmentCreateView", model);
        }

        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> FilterAilmentEdit(AilmentCreateModel model, int symptomPage = 1)
        {
            model.Symptoms = await GetAllSymptoms(symptomPage);
            return View("AilmentCreateView", model);
        }


        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> Edit(string name)
        {
            var ailmentResult = await AilmentFacade.GetAilmentsAsync(new AilmentFilterDto {Name = name});
            if (!ailmentResult.Items.Any())
            {
                return View("AilmentCreateView",
                            new AilmentCreateModel
                            {
                                    Alert = new AlertMessage($"Ailment {name} doesn't exist.", AlertMessage.MessageType.danger)
                            });
            }
            var ailment = ailmentResult.Items.First();
            var model = new AilmentCreateModel
            {
                    AilmentId = ailment.Id,
                    Symptoms = await GetAllSymptoms(1),
                    AilmentName = ailment.Name,
                    SymptomGuidsFilter = (await AilmentFacade.GetAilmentSymptomsAsync(new AilmentSymptomFilterDto {AilmentId = ailment.Id})).Items.Select(i => i.SymptomId).ToList(),
                    SymptomFilterActionName = nameof(FilterAilmentEdit)
            };
            return View("AilmentCreateView", model);
        }


        [HttpPost]
        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> Edit(AilmentCreateModel model)
        {
            var returnModel = new AilmentListModel();
            var ailmentResult = await AilmentFacade.GetAilmentsAsync(new AilmentFilterDto {Id = model.AilmentId});
            if (ailmentResult.Items.Any())
            {
                var asResults = await AilmentFacade.GetAilmentSymptomsAsync(new AilmentSymptomFilterDto
                {
                        AilmentId = model.AilmentId
                });

                asResults.Items.ToList().ForEach(async ailmentSymptom => await AilmentFacade.DeleteAilmentSymptomAsync(ailmentSymptom.Id));


                var ailment = ailmentResult.Items.First();
                ailment.Name = model.AilmentName;

                await AilmentFacade.EditAilmentAsync(ailment);

                await AilmentFacade.AddAilmentSymptoms(model.SymptomGuidsFilter.Select(s => new AilmentSymptomDto {AilmentId = ailment.Id, SymptomId = s}).ToList());

                returnModel.Alert = new AlertMessage($"Succesfully edited {model.AilmentName}", AlertMessage.MessageType.success);
            }
            else
            {
                returnModel.Alert = new AlertMessage("Editation failed - Ailment no longer exists.", AlertMessage.MessageType.danger);
            }
            return await Index(returnModel);
        }

        [HttpPost]
        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> Delete(Guid id)
        {
            var returnModel = new AilmentListModel();
            if (await AilmentFacade.DeleteAilmentAsync(id))
            {
                returnModel.Alert = new AlertMessage("Ailment was successfuly deleted.", AlertMessage.MessageType.success);
            }
            else
            {
                returnModel.Alert = new AlertMessage("Failed to delete ailment.", AlertMessage.MessageType.danger);
            }
            return await Index(returnModel);
        }

        [HttpPost]
        [PermissionAuthorize(Permission.editAilments)]
        public async Task<ActionResult> Create(AilmentCreateModel model)
        {            
            if (string.IsNullOrWhiteSpace(model.AilmentName))
            {
                ModelState.AddModelError(nameof(model.AilmentName), "The ailment's name can't be blank.");
            }
            if (model.SymptomGuidsFilter == null)
            {
                ModelState.AddModelError(nameof(model.SymptomGuidsFilter), "An ailment can't have no symptoms.");
            }
            if (!ModelState.IsValid)
            {
                var returnModel = new AilmentCreateModel
                {
                        Symptoms = await GetAllSymptoms(1),
                        SymptomFilterActionName = nameof(FilterAilmentEdit)
                };
                return View("AilmentCreateView", returnModel);
            }

            await AilmentFacade.CreateAilmentWithSymptoms(model.AilmentName, model.SymptomGuidsFilter);

            model = new AilmentCreateModel
            {
                    Symptoms = await GetAllSymptoms(1),
                    SymptomFilterActionName = nameof(FilterAilmentEdit),
                    Alert = new AlertMessage($"Ailment {model.AilmentName} succesfully created.",
                                             AlertMessage.MessageType.success),
            };
            return View("AilmentCreateView", model);
        }

        public async Task<PagedList.StaticPagedList<SymptomDto>> GetAllSymptoms(int symptomPage)
        {
            var symptomResult = await AilmentFacade.GetSymptomsAsync(new SymptomFilterDto {RequestedPageNumber = symptomPage, PageSize = symptomItemsPerPage});
            return new PagedList.StaticPagedList<SymptomDto>(symptomResult.Items, symptomPage, symptomItemsPerPage, (int) symptomResult.TotalItemsCount);
        }

    }

}

Projekt/Hospital/PresentationLayer/Views/Ailments/AilmentCreateView.cshtml
@model PresentationLayer.Models.AilmentCreateModel

@{
    ViewBag.Title = "AilmentCreateView";
}

@if (Model.AilmentId == null)
{
    <h2>New ailment</h2>
}
else
{
    <h2>Edit ailment </h2>
    if (@Model.AilmentId != null)
    {
        using (Html.BeginForm("DeleteAilmentWithReferences", "Issue", FormMethod.Post))
        {
            <input hidden value="@Model.AilmentId" name="id" />
            <button class="btn btn-danger" type="submit">Delete</button>
        }
    }

}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <input hidden value="@Model.AilmentId" name="@nameof(Model.AilmentId)" />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="row font-weight-bold">
                @Html.LabelFor(model => model.AilmentName, "Ailment Name", htmlAttributes: new { @class = "control-label col-md-12" })
            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.AilmentName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AilmentName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <div class="row font-weight-bold">
                    Symptoms
                </div>
                @{
                    Html.RenderPartial("PagedSymptoms", Model);
                    @Html.ValidationMessageFor(model => model.SymptomGuidsFilter, "", new { @class = "text-danger" })
                }
            </div>
            @if (Model.Symptoms.PageCount > 1)
            {
                <hr />
            }
        </div>



        <div class="form-group">
            @if (Model.AilmentId == null) {

                <input type="submit" value="Create" class="btn btn-default" formaction="Create" />

            } else {

                <input type="submit" value="Apply" class="btn btn-warning" formaction="Edit" />

            }
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-secondary ml-2" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekt/Hospital/PresentationLayer/Views/Ailments/AilmentsView.cshtml
@model PresentationLayer.Models.AilmentListModel
@using BusinessLayer.DataTransferObjects
@using BusinessLayer.Services.Users
@using PagedList.Mvc

@{
    ViewBag.Title = "AilmentsView";
}

<h2>
    Ailments

    @if (ViewBag.HasPermission(Permission.editAilments))
    {
        @Html.ActionLink("+ Add", "Create", null, new { @class = "btn btn-success btn-sm ml-2" })
    }

</h2>
<hr />
@if (TempData["AlertMessage"] != null)
{
    if (TempData["AlertMessage"].ToString().Contains("success"))
    {
        <div class="alert alert-success" role="alert">
            @TempData["AlertMessage"]
        </div>
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            @TempData["AlertMessage"]
        </div>
    }
}

<a href="#" data-toggle="collapse" data-target="#filter">
    <h3 class="bg-light text-dark">Filter</h3>
</a>
@using (Html.BeginForm("Index", "Ailments", FormMethod.Get, new { id = "filterForm" }))
{
    <div id="filter" class="container collapse bg-light @((Model.AilmentNameFilter != null || Model.SymptomGuidsFilter != null || Model.Symptoms.PageNumber > 1) ? "show" : "")">
        <hr />
        <div class="row">


            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-12">
                        Ailment Name
                    </div>
                    <div class="col-md-12">
                        @Html.EditorFor(m => m.AilmentNameFilter, new { htmlAttributes = new { @class = "form-control col-md-11" } })
                    </div>

                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    Symptoms
                </div>
                @{
                    Html.RenderPartial("PagedSymptoms", Model);
                }
            </div>
        </div>


        <div class="row">
            <div class="col-md-12 mt-4">
                <input type="submit" value="Filter" class="btn btn-secondary" />
                @Html.ActionLink("Reset", "Index", "Ailments", new { }, new { @class = "btn btn-outline-secondary" })
            </div>
        </div>
        <hr />

    </div>
}
@if (!Model.Ailments.Any())
{
    <div class="row">
        <div class="col-md-12">
            <i> No ailments found.</i>
        </div>
    </div>
}

@foreach (AilmentDto ailment in Model.Ailments)
{
    <div class="row">

        @Html.ActionLink(ailment.Name, "Edit", "Ailments", new { name = ailment.Name }, new { @class = "user-list col-md-12 " })

    </div>
}


@if (Model.Ailments.PageCount > 1)
{
    <hr />
    @Html.PagedListPager(Model.Ailments, page => Url.Action("Index", new { ailmentPage = page, symptomPage = Model.Symptoms.PageNumber, model = Model, AilmentNameFilter = Model.AilmentNameFilter, SymptomGuidsFilter = Model.SymptomGuidsFilter }))
}